name: Backend CI/CD

on:
  push:
    paths:
      - 'backend/**'
    branches: [main, dev]

jobs:
  build-deploy-digitalocean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.RENTEE_GHCR_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/rentee-backend:latest

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ghcr.io/${{ github.repository_owner }}/rentee-backend:latest
            docker stop rentee-backend || true
            docker rm rentee-backend || true
            docker run -d \
              --name rentee-backend \
              --restart unless-stopped \
              -p 3000:3000 \
              ghcr.io/${{ github.repository_owner }}/rentee-backend:latest

  deploy-railway:
    runs-on: ubuntu-latest
    needs: build-deploy-digitalocean
    container: ghcr.io/railwayapp/cli:latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Deploy to Railway
        run: railway up
        working-directory: ./backend