name: Backend CI/CD

on:
  push:
    paths:
      - 'backend/**'
    branches: [main, dev]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/rentee-backend:latest ./backend

      - name: Login to GHCR
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/rentee-backend:latest

      - name: Deploy over SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ghcr.io/${{ github.repository_owner }}/rentee-backend:latest
            docker stop rentee-backend || true
            docker rm rentee-backend || true
            docker run -d --name rentee-backend -p 3000:3000 ghcr.io/${{ github.repository_owner }}/rentee-backend:latest
