name: Block non-dev merges

on:
  pull_request:
    branches:
      - main

jobs:
  block-non-dev-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        run: |
          echo "PR branch: ${{ github.head_ref }}"
          if [[ "${{ github.head_ref }}" != "dev" ]]; then
            echo "Only PRs from 'dev' branch are allowed to merge into 'main'"
            exit 1
          fi
